require('user.bootstrap')
require('user.ft')
require('user.options')
require('user.plug')
require('user.theme')
require('user.icons')
require('user.cmp')
require('user.harpoon')
require('user.telescope')
require('user.lsp')
require('user.toggleterm')
require('user.colorizer')
require('user.tree')
require('user.statusbar')
require('user.undo')
require('user.whichkey')
require('user.treesitter-config')
require('user.copilot')

-- Language specific settings
require('user.languages.angular')

